import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
  SignUp,
  SignIn
} from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          
          {/* Below is the Navbar  */}
          <div className="flex justify-end items-center">
            {/* whenever we are signed in then we should see this thing */}
            <SignedIn>
              <UserButton />
            </SignedIn>
          </div>

          {/* whenever we are signed out then we should see these things */}
          <SignedOut>
            <div className="min-h-screen w-screen flex justify-center items-center absolute inset-0 z-50 bg-white">
              <SignUp/>
            </div>
          </SignedOut>

          {/* whenever we are signed in then we should see this thing */}
          <SignedIn>
            {children}
          </SignedIn>
          
        </body>
      </html>
    </ClerkProvider>
  );
}
